[build]
  base = "/"
  publish = "/out"
  command = "pnpm install --frozen-lockfile && pnpm build"

[build.environment]
  NODE_VERSION = "18.18.0"
  PNPM_VERSION = "8.10.0"
  PNPM_REGISTRY = "https://registry.npmjs.org"
  PNPM_STORE_DIR = "/opt/buildhome/.pnpm-store"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://ishkkozdnhhibcxlnvgc.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzaGtrb3pkbmhoaWJjeGxudmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODA4MTIsImV4cCI6MjA2MjQ1NjgxMn0.FSEXqLrYphZ31IOHDu5xiTb4UhGQipjTE_XjbrfIW1Q"

[functions]
  node_bundler = "esbuild"

[functions.build]
  command = "pnpm install --frozen-lockfile"
  publish = "functions"
