[build]
  base = "/"
  publish = ".next"
  command = "pnpm install --no-frozen-lockfile && pnpm build"

[build.environment]
  NODE_VERSION = "20.0.0"
  YARN_VERSION = "1.22.0"
  PNPM_VERSION = "8.10.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_BASE_PATH = ""
  NODE_OPTIONS = "--max-old-space-size=4096"
  
[build]
  command = "pnpm install --no-frozen-lockfile"
  publish = ".next"
  functions = ".netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self'; object-src 'none'; frame-src 'self' https:;"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/**/*",
    "package.json",
    "pnpm-lock.yaml",
    "*.js",
    "*.json"
  ]

[functions.build]
  command = "pnpm install --frozen-lockfile"
  publish = "functions"

[functions.api]
  handler = "api/handler.js"
  memory_size = 1024
  timeout = 10
  runtime = "nodejs18.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
